export const ROUTES = {
    root: "",
    login: "/login",
    home: "/home",
    AVPOverride: "/home/avp-override",
    account: "/home/account",
    record_filter: "/home/record-filter",
    coa: "/home/coa",
    nas_config: "/home/nas-config",
    nas_attribute_map: "/home/attribute-map",
    parameter_setting: "/home/parameter-settings",
    plan_type: "/home/plan/type",
    plan_attribute: "/home/plan/attributes",
    plan_parameter: "/home/plan/parameters",
    plan: "/home/plan",
    subscribers: "/home/subscribers",
}
