export const ROUTES = {
    root: "",
    login: "/login",
    home: "/home",
    AVPOverride: "/system/accounting/avp-override",
    account: "/system/accounting/account",
    record_filter: "/system/accounting/record-filter",
    coa: "/co-dm/coa",
    nas_config: "/nas/nas-manage",
    nas_attribute_map: "/nas/attribute-group",
    parameter_setting: "/home/parameter-settings",
    plan_type: "/plan/type",
    plan_attribute: "/plan/attributes",
    plan_parameter: "/parameters/manage-parameters",
    plan: "/plan",
    subscribers: "/home/subscribers",
}
